/*
 * a2g_integration.h — A2G C/C++ Integration Wrapper
 * ====================================================
 * Include this header instead of (or in addition to) a2g.h when integrating
 * a2g-ffi into platform middleware.  It re-exports the full cbindgen-generated
 * ABI from a2g.h and adds the file-level contract documentation that is present
 * in the Rust module doc but not emitted by cbindgen.
 *
 * DO NOT modify this header to change the ABI.  All ABI definitions live in
 * a2g.h (generated by cbindgen from crates/a2g-ffi/src/lib.rs).  This file is
 * annotation-only.
 *
 *
 * ABI STABILITY CONTRACT (ADR-0009)
 * ---------------------------------
 * The binary ABI is stable within a major version:
 *   - A2gDecision integer values are fixed and will not be reordered.
 *   - A2gVerdictHandle and A2gVerifiedStateHandle are opaque — their size and
 *     layout are not part of the public ABI; never embed them by value.
 *   - New functions may be added in minor releases (additive, ABI-compatible).
 *   - Functions will not be removed or have their signatures changed without a
 *     major-version bump and a deprecation period.
 *
 *
 * THREAD-SAFETY CONTRACT
 * ----------------------
 * Each A2gVerdictHandle is independently owned by the caller.  Concurrent
 * calls using *different* handles are safe — the library holds no process-wide
 * mutable state that is accessed during a2g_decide / a2g_decide_with_approval.
 *
 * a2g_verified_state_operator_trusted() is also thread-safe.
 *
 * Do NOT share a single handle across threads without external
 * synchronisation.  The handle itself is not internally synchronized — it is a
 * plain heap allocation that the caller owns exclusively.
 *
 * The per-process binding-integrity key (used to MAC Phase 1 pending-approval
 * bindings) is initialized once via a thread-safe OnceLock and is read-only
 * thereafter.  No additional synchronisation is required from the caller.
 *
 *
 * OWNERSHIP MODEL
 * ---------------
 *
 *  Type                       Allocator            How to free
 *  ───────────────────────────────────────────────────────────────────────────
 *  A2gVerdictHandle *         a2g_decide()         a2g_verdict_free()
 *                             a2g_decide_with_approval()
 *
 *  A2gVerifiedStateHandle *   a2g_verified_state_  a2g_verified_state_free()
 *                             operator_trusted()
 *
 *  char * (mandate TOML)      a2g_test_mandate_    a2g_string_free()
 *                             toml()
 *
 *  const char * (accessors)   library-internal     DO NOT free; valid until
 *  e.g. a2g_verdict_id()                           a2g_verdict_free() on owner
 *
 * Passing NULL to any *_free function is always a safe no-op.
 *
 *
 * ERROR CODE QUICK REFERENCE
 * --------------------------
 *
 *  A2G_DECISION_ALLOW            (0)  — Tool call is permitted.  Proceed.
 *  A2G_DECISION_DENY             (1)  — Tool call is refused.  Abort.
 *  A2G_DECISION_EXPIRED          (2)  — Mandate TTL has elapsed.  Reject mandate.
 *  A2G_DECISION_PENDING_APPROVAL (3)  — Human approval required (Phase 1).
 *                                       Persist binding_json; call Phase 2 API
 *                                       once the approver returns a grant.
 *  A2G_DECISION_ERROR           (-1)  — Internal error, invalid input, or
 *                                       tampered binding MAC.  Abort.
 *
 *
 * PHASE 1 → PHASE 2 SUMMARY
 * --------------------------
 * When a2g_decide() returns A2G_DECISION_PENDING_APPROVAL:
 *
 *   1. Extract the MAC-protected binding token:
 *        const char *binding = a2g_verdict_binding_json(h);
 *
 *   2. Forward binding_id + request_hash + escalate_to (from the binding JSON)
 *      to your approval backend (operator console, mobile push, etc.).
 *
 *   3. When the human approver returns a signed ApprovalGrant JSON, call:
 *        a2g_decide_with_approval(mandate, tool, params, state,
 *                                 binding, grant_json, &out_verdict);
 *
 *   Do NOT modify any field of binding_json between steps 1 and 3.  The MAC
 *   covers every field; any modification returns A2G_DECISION_ERROR.
 *
 * See docs/INTEGRATION.md for the full integration sequence and architecture.
 */

#ifndef A2G_INTEGRATION_H
#define A2G_INTEGRATION_H

#include "a2g.h"

/* ABI version token for compile-time checks. */
#define A2G_ABI_VERSION_MAJOR 0
#define A2G_ABI_VERSION_MINOR 1

/*
 * Convenience: test whether a decision requires Phase 2 follow-up.
 *   if (A2G_NEEDS_APPROVAL(d)) { ... forward to approver backend ... }
 */
#define A2G_NEEDS_APPROVAL(d)  ((d) == A2G_DECISION_PENDING_APPROVAL)

/*
 * Convenience: test whether a decision is terminal (no further action needed).
 */
#define A2G_IS_TERMINAL(d)     ((d) == A2G_DECISION_ALLOW  || \
                                 (d) == A2G_DECISION_DENY   || \
                                 (d) == A2G_DECISION_EXPIRED || \
                                 (d) == A2G_DECISION_ERROR)

#endif /* A2G_INTEGRATION_H */
